Support publisher proof
brave/brave-core-crx-packager pull request #337
Opened 2022-02-16 07:46 UTC by atuchin-m

Resolves https://github.com/brave/brave-browser/issues/873

The purpose of this PR is to add extra signing (a publisher proof) to all brave CRX.
The plan:
[DONE] (brave-core) add code to generate publisher proof
[DONE] (devops) add new credentials
[in progress](devops) change browser from Chrome to Brave (maybe Brave Nightly?)
[in progress] (devops) pass the credentials to  [brave-core-crx-packager](https://github.com/brave/brave-core-crx-packager) signing scripts
[here] (brave-core-crx-packager) pass the new key to Brave (when we making crx by passing a special command-line)

The devops changes is in progress

2022-02-16 07:47 UTC, atuchin-m commented on scripts/packageBraveAdsResourcesComponent.js
> +     .option('-d, --keys-directory <dir>', 'directory containing private keys for signing crx files'))
To avoid adding more copy/paste I've extracted the common options to a new function in `util.js`

2022-02-16 07:48 UTC, atuchin-m commented on scripts/packageBraveAdsResourcesComponent.js
> - if (!commander.binary) {
This is moved to `generateCRXFile` in `util`

2022-02-16 16:18 UTC, SergeyZhukovsky approved these changes
++. But better to wait for others review. I'm not very familiar with crx signing.

2022-02-17 08:33 UTC, spylogsster requested changes
pls do not merge until https://ci.brave.com/view/all-extensions/job/brave-core-ext-ipfs-component-publish-dev/ build from this branch will be success

2022-02-17 22:35 UTC, linhkikuchi commented
@atuchin-m  I need to add `--publisher-proof-key` during npm package for all pipelines, but some still need to run on master to publish, so it will hit `error: unknown option `--publisher-proof-key'. Would it be possible to have a change to master first to make sure we can pass `--publisher-proof-key` and it's still ok (just not signing additional key).

2022-03-08 07:30 UTC, spylogsster approved these changes

2022-03-08 23:34 UTC, merged